services:
  server:
    image: db_server:3.0.1_profiling-466c204
    container_name: db_server
    ports:
      - 8080:80
    environment:
      DB_USER: ${DB_USER:?error}
      DB_PASSWORD: ${DB_PASSWORD:?error}
      DB_DATABASE: ${DB_DATABASE:?error}
      DB_ADDRESS: mysql
      DB_ROOT_PWD: ${DB_ROOT_PWD:?error}
      DB_PORT: 3306
      PORT: 80
      USE_METRICS: true
      USE_PROFILING: true
      PYROSCOPE_URL: "http://pyroscope:4040"
      COLLECTOR_URL: "http://alloy:4318/v1"
    mem_limit: 512m
    cpus: 1.0
    depends_on:
      - mysql
      - cadvisor
      - alloy
  mysql:
    image: mysql:8.0
    container_name: mysql_simple_server
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: ${DB_USER:?error}
      MYSQL_PASSWORD: ${DB_PASSWORD:?error}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PWD:?error}
      MYSQL_DATABASE: ${DB_DATABASE:?error}
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    command:
      - run
      - "/etc/alloy/config.alloy"
      - "--server.http.listen-addr=0.0.0.0:12345"
      - "--disable-reporting=true"
    volumes:
      - ./config/alloy.hcl:/etc/alloy/config.alloy:ro
    ports:
      # - "4318:4318"
      # - "9464:9464"
      - "12345:12345"
  k6:
    image: grafana/k6:latest
    volumes:
      - ./k6:/scripts
    # command: run /scripts/test.js -o opentelemetry
    entrypoint: ["k6"]
    environment:
      - K6_OTEL_EXPORTER_TYPE=http
      - K6_OTEL_HTTP_EXPORTER_ENDPOINT=alloy:4318
      - K6_OTEL_HTTP_EXPORTER_INSECURE=true
      - K6_OTEL_SERVICE_NAME=k6-load-test
      - K6_OTEL_EXPORT_INTERVAL=5s
    depends_on:
      - alloy
      - server
    profiles:
      - testing
  prom:
    image: prom/prometheus
    ports:
      - "9099:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--web.enable-lifecycle"
      - "--web.enable-remote-write-receiver"
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    depends_on:
      - alloy

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - gf_security_admin_user=admin
      - gf_security_admin_password=admin
      - GF_PLUGINS_PREINSTALL_SYNC=grafana-pyroscope-app
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prom
    restart: unless-stopped
  pyroscope:
    image: grafana/pyroscope
    command:
      - -self-profiling.disable-push=true
    ports:
      - "9097:4040"
volumes:
  grafana_data:
  k6_results:
