version: "3"
tasks:
  docker_build:
    vars:
      COMMIT_HASH:
        sh: "git rev-parse --short HEAD"
      IMAGE_NAME: db_server
      HISTORY_FILE_NAME: docker_versions.yaml
      DATETIME:
        sh: 'date +"%d.%m.%Y %H:%M"'
      VERSION: "{{.CLI_ARGS}}"
      IMAGE_TAG: "{{.IMAGE_NAME}}:{{.VERSION}}-{{.COMMIT_HASH}}"
    aliases:
      - db
    preconditions:
      - sh: test -n "{{.CLI_ARGS}}"
        msg: "Version not found, specify one: -- v1.2.3"
    cmds:
      - docker build -t {{.IMAGE_TAG}} .
      - |
        if [ ! -f {{.HISTORY_FILE_NAME}} ]; then
          echo "builds:" > {{.HISTORY_FILE_NAME}}
        fi
      - |
        cat >> {{.HISTORY_FILE_NAME}} <<EOF
        - {{.VERSION}}:
          name: {{.IMAGE_TAG}}
          datetime: {{.DATETIME}}
        EOF
      - echo "Image {{.IMAGE_TAG}} built successfully"

    desc: Build the Docker image with commit and version.
  migrate_run:
    aliases:
      - mr
    cmd: "cargo sqlx migrate run --target-version {{.CLI_ARGS}}"
    desc: Run migration with specific version
  migrate_revert:
    aliases:
      - mrm
    cmd: "cargo sqlx migrate revert --target-version {{.CLI_ARGS}}"
    desc: Revert migration with specific version
  run_profile_test:
    aliases:
      - pt
    cmd: "docker compose run --rm k6 run {{.CLI_ARGS}} -o opentelemetry"
    desc: >
      Run K6 instance with a file provided as argument and output to otel-collector.
      WARNING: Path must locate test-file inside container: -- /scripts/test.js
