{
 "title": "Todo server status",
 "time": { "from": "2026-02-18T19:48:28.731Z", "to": "2026-02-18T19:50:33.132Z" },
 "refresh": "auto",
 "panels": [
  { "title": "k6", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "k6 Requests total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_reqs_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "http_reqs_total",
   "type": "timeseries",
   "description": "\n\n**Type:** *counter*\n\n",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(irate(http_reqs_total{instance=\"otel-collector:9464\", job=\"otel-collector\"}[$__interval]))",
     "legendFormat": "sum(rate)"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 1 },
   "targets": [
    { "expr": "vus", "legendFormat": "__auto" }
   ]
  },
  { "title": "Server metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "http_requests_total",
   "type": "timeseries",
   "description": "Shows amount of http requests\n\n**Type:** *counter*\n\n",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{ }[$__rate_interval]))",
     "legendFormat": "sum(rate)"
    }
   ]
  },
  {
   "title": "Requests total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (http_requests_total{instance=\"otel-collector:9464\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "requests_latency_bucket",
   "type": "timeseries",
   "description": "Cumulative counters for the observation buckets (Shows time for request to take)\n\n**Type:** *counter*\n\n",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(requests_latency_bucket{exported_job=\"todo_metrics\"}[1m])))"
    }
   ]
  },
  { "title": "CAdvisor stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "container_cpu_cfs_throttled_seconds_total",
   "type": "timeseries",
   "description": "Total time duration the container has been throttled.\n\n**Type:** *counter*\n\n",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{image=\"db_server:2.1.3-c47fd8b\"}[$__rate_interval]))",
     "legendFormat": "sum(rate)"
    }
   ]
  },
  {
   "title": "container_memory_usage_bytes",
   "type": "timeseries",
   "description": "Current memory usage in bytes, including all memory regardless of when it was accessed\n\n**Type:** *gauge*\n\n",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{image=\"db_server:2.1.3-c47fd8b\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "server cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 13, "y": 15 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{image=\"db_server:2.1.3-c47fd8b\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}