receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:
#    timeout: 5s
#    send_batch_size: 1000

exporters:
  prometheus:
    endpoint: "0.0.0.0:9464"
  # otlp/jaeger:
  #   endpoint: "http://jaeger:4317"
  #   tls:
  #     insecure: true
  file:
    path: /tmp/otel.json
  debug:

service:
  pipelines:
    # traces:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [otlp/jaeger, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug]
